name:                refinedfuthark
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Description placeholder

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- containers
- mainland-pretty

library:
  source-dirs: src

executables:
  refinedfuthark:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refinedfuthark

tests:
  refinedfuthark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    #- HUnit
    - tasty-hunit
    - refinedfuthark
